# Generated by Django 6.0 on 2025-12-26 23:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kassenabrechnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=django.utils.timezone.now)),
                ('kassenstand_anfang', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('anzahl_kinder', models.IntegerField(default=0)),
                ('anzahl_erwachsene', models.IntegerField(default=0)),
                ('anzahl_tee', models.IntegerField(default=0)),
                ('preis_kinder', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('preis_erwachsene', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('preis_tee', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('rueckgeldspende', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('anzahl_50euro', models.IntegerField(default=0)),
                ('anzahl_20euro', models.IntegerField(default=0)),
                ('anzahl_10euro', models.IntegerField(default=0)),
                ('anzahl_5euro', models.IntegerField(default=0)),
                ('anzahl_2euro', models.IntegerField(default=0)),
                ('anzahl_1euro', models.IntegerField(default=0)),
                ('anzahl_50cent', models.IntegerField(default=0)),
                ('anzahl_20cent', models.IntegerField(default=0)),
                ('anzahl_10cent', models.IntegerField(default=0)),
                ('gegeben', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rueckgeld', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kassenabrechnung',
                'verbose_name_plural': 'Kassenabrechnungen',
                'ordering': ['-datum'],
            },
        ),
    ]
