# Generated by Django 5.0 on 2025-12-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KassenEinstellungen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bezeichnung_position1', models.CharField(default='Kinder', max_length=50)),
                ('bezeichnung_position2', models.CharField(default='Erwachsene', max_length=50)),
                ('bezeichnung_position3', models.CharField(default='Tee', max_length=50)),
                ('preis_position1', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('preis_position2', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('preis_position3', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kassen-Einstellungen',
                'verbose_name_plural': 'Kassen-Einstellungen',
            },
        ),
        migrations.AlterField(
            model_name='kassenabrechnung',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
