# Generated by Django 5.0 on 2025-12-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasse', '0002_kasseneinstellungen_alter_kassenabrechnung_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kassenabrechnung',
            name='gesamt_erwachsene',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kassenabrechnung',
            name='gesamt_kinder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kassenabrechnung',
            name='gesamt_tee',
            field=models.IntegerField(default=0),
        ),
    ]
