# Generated by Django 5.0 on 2025-12-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasse', '0003_kassenabrechnung_gesamt_erwachsene_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kassenabrechnung',
            name='gesamt_bargeld',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
