# Generated by Django 5.0 on 2025-12-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasse', '0004_kassenabrechnung_gesamt_bargeld'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasseneinstellungen',
            name='kassenstand_anfang_default',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Standard-Kassenstand zu Beginn', max_digits=10),
        ),
    ]
